font_family Hack Nerd Font
font_size 12

map ctrl + backspace send_text all \x17

confirm_os_window_close 0

KITTY_ENABLE_WAYLAND=1

hide_window_decorations yes

background_opacity 0.8
dynamic_background_opacity yes
enable_audio_bell no
